{"name": "test_verify_login_with_invalid_username", "status": "passed", "start": 1721831452328, "stop": 1721831453068, "uuid": "1001988f-9b2c-48e4-918d-c44057d14b09", "historyId": "f5d1e6bc02260ccd5e4bd47a47c4a927", "testCaseId": "f5d1e6bc02260ccd5e4bd47a47c4a927", "fullName": "test.test_Login.TestLogin#test_verify_login_with_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Raunak"}, {"name": "thread", "value": "33780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_Login"}]}